CREATE TABLE IF NOT EXISTS auth_user_session_state (
    user_id UUID PRIMARY KEY,
    session_version BIGINT NOT NULL DEFAULT 1,
    force_logout_at TIMESTAMP,
    create_time TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    update_time TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);
